# Example: Override respecConfig for W3C deployment and validators.
name: Echidna Auto-publish
on:
  pull_request:
    paths: ["**"]
  push:
    branches: [gh-pages]
    paths: ["**"]
jobs:
  main:
    name: Echidna Auto-publish WD
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          VALIDATE_LINKS: false
          VALIDATE_MARKUP: true
          ACTIONS_STEP_DEBUG: true
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2024/09/24-did-minutes.html#r02
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
            shortName: did-resolution
